version: "3.8"

services:
  api:
    build: .
    container_name: calculate-taxes-api
    ports:
      - "8080:58982"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - REDIS_CONNECTION=redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app-network  

  redis:
    image: redis:latest
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - app-network      

volumes:
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge